name: book_finder_app
description: "App em Flutter para buscar livros na Open Library e salvar favoritos localmente."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Requisições HTTP para a API pública da Open Library.
  http: ^1.2.0

  # Persistência local dos livros favoritos entre execuções do app.
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
